// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaXzcDPhrdua1xTKTW8P0AbgnNKt-_suw',
    appId: '1:1094429859231:web:3bda33de9b445ef2a1f1aa',
    messagingSenderId: '1094429859231',
    projectId: 'travel-diary-5bb1f',
    authDomain: 'travel-diary-5bb1f.firebaseapp.com',
    storageBucket: 'travel-diary-5bb1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjBNdCCIodUhBISLkBZtj56sfCCi5HHp0',
    appId: '1:1094429859231:android:e9f79bef8d6f0dc7a1f1aa',
    messagingSenderId: '1094429859231',
    projectId: 'travel-diary-5bb1f',
    storageBucket: 'travel-diary-5bb1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTaNERfdWZS3491zZebbEHf-2DllZiUmE',
    appId: '1:1094429859231:ios:818692f18badf7fea1f1aa',
    messagingSenderId: '1094429859231',
    projectId: 'travel-diary-5bb1f',
    storageBucket: 'travel-diary-5bb1f.firebasestorage.app',
    iosBundleId: 'br.com.luisa.dev.travelDiary',
  );
}
